# Generated by Django 4.2.16 on 2024-11-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="location",
        ),
        migrations.RemoveField(
            model_name="company",
            name="revenue",
        ),
        migrations.AddField(
            model_name="company",
            name="country",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="company",
            name="domain",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="company",
            name="linkedin_url",
            field=models.URLField(default=""),
        ),
        migrations.AddField(
            model_name="company",
            name="locality",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="company",
            name="size_range",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="company",
            name="year_founded",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
