# Generated by Django 4.2.16 on 2024-11-30 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0002_remove_company_location_remove_company_revenue_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="current_employee_estimate",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="total_employee_estimate",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="country",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="company",
            name="domain",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="linkedin_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="locality",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="size_range",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
